// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8gzRPSV18b--gAsyifjtIMAPsOn5JyDc',
    appId: '1:525737552936:web:65d7462abe74f6a05ed91d',
    messagingSenderId: '525737552936',
    projectId: 'tutorial-flutter-620bb',
    authDomain: 'tutorial-flutter-620bb.firebaseapp.com',
    storageBucket: 'tutorial-flutter-620bb.appspot.com',
    measurementId: 'G-DC9XZH3PR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4hdvSo5scr_A5Na-yO0PEfLZUCH74Qhc',
    appId: '1:525737552936:android:71017f95c035bb8c5ed91d',
    messagingSenderId: '525737552936',
    projectId: 'tutorial-flutter-620bb',
    storageBucket: 'tutorial-flutter-620bb.appspot.com',
  );
}
